name: ruff
on:
  push:
    # branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/ruff-action@v3
